### ISSUE TITLE
Provide GitHub releases

### ISSUE THREAD

**Issue by krokofant** [Tinkoff/ng-web-apis#30]
Please provide GitHub releases so that it's easier to watch when there are new releases

**Comment by waterplea** [comment]
We have tags in releases:
https://github.com/ng-web-apis/common/tags
And we have changelog with descriptions:
https://github.com/ng-web-apis/common/blob/master/CHANGELOG.md

Doesn't this serve the purpose?

**Comment by krokofant** [comment]
@waterplea Unfortunately not. The tags are not considered releases in the GitHub watching feature.

![image](https://user-images.githubusercontent.com/5908498/149754120-f326c808-ec12-44db-9f1d-905ec2d0491d.png)
![image](https://user-images.githubusercontent.com/5908498/149754190-c5a4f734-57e0-41e7-8d6e-5d8f04c4abc4.png)

### Here's an example of a _new release_ notification from another repo
![image](https://user-images.githubusercontent.com/5908498/149760158-6a7070dd-ff2d-44fc-bcc2-263a57231ee3.png)

**Comment by waterplea** [comment]
Got it, thank you for highlighting this. We'll see how we can improve our pipelines!
